In [1]:
import numpy as np


feature_map = np.array([
    [-2,  3, -1],
    [ 4, -5,  2],
    [-3,  1,  6]
])


def relu(x):
    return np.maximum(0, x)


result = relu(feature_map)

print("Before ReLU:")
print(feature_map)

print("\nAfter ReLU:")
print(result)

Before ReLU:
[[-2  3 -1]
 [ 4 -5  2]
 [-3  1  6]]

After ReLU:
[[0 3 0]
 [4 0 2]
 [0 1 6]]
