In [2]:
import numpy as np


# 1. Our image
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
])


# 2. Our filter/kernel
kernel = np.array([
    [-1, -1, -1],
    [ 0,  0,  0],
    [ 1,  1,  1]
])




In [3]:
# 3. Convolution
def conv2d(image, kernel):

    h, w = image.shape
    kh, kw = kernel.shape

    output = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):

            patch = image[i:i+kh, j:j+kw]

            output[i, j] = np.sum(patch * kernel)

    return output




In [4]:
# 4. ReLU
def relu(x):
    return np.maximum(0, x)




In [7]:
def max_pool2d(x):

    h, w = x.shape

    new_h = h // 2
    new_w = w // 2

    output = np.zeros((new_h, new_w))

    for i in range(new_h):
        for j in range(new_w):

            patch = x[i*2:i*2+2, j*2:j*2+2]

            output[i, j] = np.max(patch)

    return output



In [8]:
# 6. Run the CNN
feature_map = conv2d(image, kernel)

activated = relu(feature_map)

pooled = max_pool2d(activated)




In [9]:
# 7. Display everything
print("IMAGE:")
print(image)

print("\nFEATURE MAP:")
print(feature_map)

print("\nAFTER RELU:")
print(activated)

print("\nAFTER MAX POOLING:")
print(pooled)

IMAGE:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

FEATURE MAP:
[[ 2.  3.  2.]
 [ 0.  0.  0.]
 [-2. -3. -2.]]

AFTER RELU:
[[2. 3. 2.]
 [0. 0. 0.]
 [0. 0. 0.]]

AFTER MAX POOLING:
[[3.]]
