In [2]:
import numpy as np


feature_map = np.array([
    [0, 3, 0, 2],
    [4, 0, 2, 1],
    [0, 1, 6, 3],
    [2, 5, 1, 0]
])




In [3]:
def max_pool2d(x):

    h, w = x.shape

    output = np.zeros((h // 2, w // 2))

    for i in range(0, h, 2):
        for j in range(0, w, 2):

            patch = x[i:i+2, j:j+2]

            output[i//2, j//2] = np.max(patch)

    return output




In [4]:
result = max_pool2d(feature_map)

print("Before Max Pooling:")
print(feature_map)

print("\nAfter Max Pooling:")
print(result)

Before Max Pooling:
[[0 3 0 2]
 [4 0 2 1]
 [0 1 6 3]
 [2 5 1 0]]

After Max Pooling:
[[4. 2.]
 [5. 6.]]
