In [1]:
import numpy as np

image = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
])

kernel = np.array([
    [-1, -1, -1],
    [ 0,  0,  0],
    [ 1,  1,  1]
])



In [2]:

def conv2d(image, kernel):

    h, w = image.shape
    kh, kw = kernel.shape

    output = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):

            patch = image[i:i+kh, j:j+kw]

            output[i, j] = np.sum(patch * kernel)

    return output




In [3]:
result = conv2d(image, kernel)

print("Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nFeature Map:")
print(result)

Image:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

Kernel:
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]

Feature Map:
[[ 2.  3.  2.]
 [ 0.  0.  0.]
 [-2. -3. -2.]]
